# Generated by Django 6.0.7 on 2026-08-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_service_duration_shopinfo_payment_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('online', 'Online'), ('phone', 'Phone Call'), ('walk_in', 'Walk-In'), ('blocked', 'Blocked Time')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='booking_payments/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='website.service'),
        ),
    ]
