# Generated by Django 6.0.7 on 2026-08-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
    ]
