# Generated by Django 6.0.7 on 2026-08-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_shopinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='telegram_reminder_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
